appName: cloudio-backend
namespace: cloudio
replicaCount: 1
image:
  repository: 102586998566.dkr.ecr.eu-west-1.amazonaws.com/cloudio-app
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 30081
