apiVersion: v1
kind: Service
metadata:
  name: cloudio-db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cloudio-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
